### ISSUE TITLE
Add more libraries 

### ISSUE THREAD

**Issue by ProMode7** [ProMode7/android-awesome-libraries#1]
If you come across any such awesome library or resource that you think you can add then drop the link here or create a pull request.

**Comment by imaaquibali** [comment]
this issue is included in hacktoberfest or not?

**Comment by ProMode7** [comment]
@AaquibAli  yes it is included. You can see the labels added to the repo to confirm also.

**Comment by shubham423** [comment]
how to add labels to pr?

**Comment by ProMode7** [comment]
You can't add it. Only the owner of the repo can do that. Don't worry about that the repo has the required label so no need to add label exclusively to the PRs.

**Comment by azimsidd** [comment]
@ProMode7 , I want to contribute in this code. I know some more libraries for image loading and caching. Can you please assign this issue to me.
